#!/usr/bin/env Rscript

options(repos=structure(c(CRAN="https://cloud.r-project.org/")))

dir.create("~/local/R/packages",recursive=TRUE,showWarnings=FALSE)

.libPaths('~/local/R/packages')

source("https://dahl.byu.edu/latest/bamboo")
