package org.ddahl

package object bamboo {

  val MajorVersion = "<<AUTOGENERATED>>"
  val FullVersion = "<<AUTOGENERATED>>"

  type Block = Tuple2[String,Int]
  type SSBlocks = List[Block]

  val AAOrder = Array("A","R","N","D","C","E","Q","G","H","I","L","K","M","F","P","S","T","W","Y","V")
  val AAIndexPairs = AAOrder.zipWithIndex
  val AAIndexMap = AAIndexPairs.toMap

  val SSOrder = Array("H","E","T","C","K","O","S")
  val SSIndexPairs = SSOrder.zipWithIndex
  val SSIndexMap = SSIndexPairs.toMap

}

